# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

import logging as log
import os
import pprint
import subprocess
import sys
from pathlib import Path
import shutil
import stat
import tempfile
from bs4 import BeautifulSoup

import hjson
from CfgJson import set_target_attribute
from LauncherFactory import get_launcher_cls
from Scheduler import Scheduler
from utils import (VERBOSE, clean_odirs, find_and_substitute_wildcards,
                   md_results_to_html, mk_path, rm_path, subst_wildcards)


# Interface class for extensions.
class FlowCfg():
    '''Base class for the different flows supported by dvsim.py

    The constructor expects some parsed hjson data. Create these objects with
    the factory function in CfgFactory.py, which loads the hjson data and picks
    a subclass of FlowCfg based on its contents.
    '''

    # Set in subclasses. This is the key that must be used in an hjson file to
    # tell dvsim.py which subclass to use.
    flow = None

    # Can be overridden in subclasses to configure which wildcards to ignore
    # when expanding hjson.
    ignored_wildcards = []

    def __str__(self):
        return pprint.pformat(self.__dict__)

    def __init__(self, flow_cfg_file, hjson_data, args, mk_config):
        # Options set from command line
        # Uniquify input items, while preserving the order.
        self.items = list(dict.fromkeys(args.items))
        self.list_items = args.list
        self.select_cfgs = args.select_cfgs
        self.flow_cfg_file = flow_cfg_file
        self.args = args
        self.scratch_root = args.scratch_root
        self.branch = args.branch
        self.job_prefix = args.job_prefix
        self.gui = args.gui
        self.gui_debug = args.gui_debug
        if self.gui_debug:
            self.gui = 1

        self.interactive = args.interactive

        # Options set from hjson cfg.
        self.project = ""
        self.scratch_path = ""
        self.scratch_base_path = ""

        # Add exports using 'exports' keyword - these are exported to the child
        # process' environment.
        self.exports = []

        # Add overrides using the overrides keyword - existing attributes
        # are overridden with the override values.
        self.overrides = []

        # List of cfgs if the parsed cfg is a primary cfg list
        self.cfgs = []

        # Add a notion of "primary" cfg - this is indicated using
        # a special key 'use_cfgs' within the hjson cfg.
        self.is_primary_cfg = False

        # For a primary cfg, it is the aggregated list of all deploy objects
        # under self.cfgs. For a non-primary cfg, it is the list of items
        # slated for dispatch.
        self.deploy = []

        # Timestamp
        self.timestamp_long = args.timestamp_long
        self.timestamp = args.timestamp

        # Results
        self.errors_seen = False
        self.rel_path = ""
        self.results_title = ""
        self.revision = ""
        self.results_server_prefix = ""
        self.results_server_cmd = ""
        self.css_file = os.path.join(
            os.path.dirname(os.path.realpath(__file__)), "style.css")
        # `self.results_*` below will be updated after `self.rel_path` and
        # `self.scratch_base_root` variables are updated.
        self.results_dir = ""
        self.results_page = ""
        self.results_server_path = ""
        self.results_server_dir = ""
        self.results_server_page = ""
        self.results_server_url = ""
        self.results_html_name = ""

        # Full results in md text
        self.results_md = ""
        # Selectively sanitized md results to be published
        self.publish_results_md = ""
        self.sanitize_publish_results = False
        # Summary results, generated by over-arching cfg
        self.results_summary_md = ""

        # Merge in the values from the loaded hjson file. If subclasses want to
        # add other default parameters that depend on the parameters above,
        # they can override _merge_hjson and add their parameters at the start
        # of that.
        self._merge_hjson(hjson_data)

        # Is this a primary config? If so, we need to load up all the child
        # configurations at this point. If not, we place ourselves into
        # self.cfgs and consider ourselves a sort of "degenerate primary
        # configuration".
        self.is_primary_cfg = 'use_cfgs' in hjson_data

        # If it's a primary_cfg, it's results can be grouped for reporting
        # purposes in the 'use_cfgs' section of the hjson. If that's the case
        # we group the reports
        self.batchgroups = False

        if not self.is_primary_cfg:
            self.cfgs.append(self)
        else:
            if isinstance(self.use_cfgs, dict):
                for batchgroup, entries in self.use_cfgs.items():
                    for entry in entries:
                        self._load_child_cfg(entry, mk_config, batchgroup)
                self.batchgroups = True
            elif isinstance(self.use_cfgs, list):
                for entry in self.use_cfgs:
                    self._load_child_cfg(entry, mk_config)
            else:
                log.error("use_cfgs must be either a dict of batchgroups",
                          " or a list of configs")
                sys.exit(1)

        if self.rel_path == "":
            self.rel_path = os.path.dirname(self.flow_cfg_file).replace(
                self.proj_root + '/', '')

        # Process overrides before substituting wildcards
        self._process_overrides()

        # Expand wildcards. If subclasses need to mess around with parameters
        # after merging the hjson but before expansion, they can override
        # _expand and add the code at the start.
        self._expand()

        # Construct the path variables after variable expansion.
        self.results_dir = (Path(self.scratch_path) / "reports" / "latest")
        self.results_page = (self.results_dir / self.results_html_name)

        tmp_path = (self.results_server + "/" + self.rel_path +
                    "/latest/" + self.results_html_name)
        self.results_server_page = self.results_server_prefix + tmp_path
        self.results_server_url = "https://" + tmp_path

        # Run any final checks
        self._post_init()

    def _merge_hjson(self, hjson_data):
        '''Take hjson data and merge it into self.__dict__

        Subclasses that need to do something just before the merge should
        override this method and call super()._merge_hjson(..) at the end.

        '''
        for key, value in hjson_data.items():
            set_target_attribute(self.flow_cfg_file, self.__dict__, key, value)

    def _expand(self):
        '''Called to expand wildcards after merging hjson

        Subclasses can override this to do something just before expansion.

        '''
        # If this is a primary configuration, it doesn't matter if we don't
        # manage to expand everything.
        partial = self.is_primary_cfg

        # If custom dump script is exist, replace with run_script attribute.
        if self.args.dump_script is not None:
            self.run_script = '{proj_root}/' + self.args.dump_script

        self.__dict__ = find_and_substitute_wildcards(self.__dict__,
                                                      self.__dict__,
                                                      self.ignored_wildcards,
                                                      ignore_error=partial)

    def _post_init(self):
        # Run some post init checks
        if not self.is_primary_cfg:
            # Check if self.cfgs is a list of exactly 1 item (self)
            if not (len(self.cfgs) == 1 and self.cfgs[0].name == self.name):
                log.error("Parse error!\n%s", self.cfgs)
                sys.exit(1)

    def create_instance(self, mk_config, flow_cfg_file, batchgroup=None):
        '''Create a new instance of this class for the given config file.

        mk_config is a factory method (passed explicitly to avoid a circular
        dependency between this file and CfgFactory.py).

        '''
        new_instance = mk_config(flow_cfg_file)

        # Sanity check to make sure the new object is the same class as us: we
        # don't yet support heterogeneous primary configurations.
        if type(self) is not type(new_instance):
            log.error("{}: Loading child configuration at {!r}, but the "
                      "resulting flow types don't match: ({} vs. {}).".format(
                          self.flow_cfg_file, flow_cfg_file,
                          type(self).__name__,
                          type(new_instance).__name__))
            sys.exit(1)

        new_instance.batchgroup = batchgroup

        return new_instance

    def _load_child_cfg(self, entry, mk_config, batchgroup=None):
        '''Load a child configuration for a primary cfg'''
        if type(entry) is str:
            # Treat this as a file entry. Substitute wildcards in cfg_file
            # files since we need to process them right away.
            cfg_file = subst_wildcards(entry, self.__dict__, ignore_error=True)
            self.cfgs.append(self.create_instance(mk_config, cfg_file, batchgroup))

        elif type(entry) is dict:
            # Treat this as a cfg expanded in-line
            temp_cfg_file = self._conv_inline_cfg_to_hjson(entry)
            if not temp_cfg_file:
                return
            self.cfgs.append(self.create_instance(mk_config, temp_cfg_file, batchgroup))

            # Delete the temp_cfg_file once the instance is created
            log.log(VERBOSE, "Deleting temp cfg file:\n%s", temp_cfg_file)
            rm_path(temp_cfg_file, ignore_error=True)

        else:
            log.error(
                "Type of entry \"%s\" in the \"use_cfgs\" key is invalid: %s",
                entry, str(type(entry)))
            sys.exit(1)

    def _conv_inline_cfg_to_hjson(self, idict):
        '''Dump a temp hjson file in the scratch space from input dict.
        This method is to be called only by a primary cfg'''

        if not self.is_primary_cfg:
            log.fatal("This method can only be called by a primary cfg")
            sys.exit(1)

        name = idict["name"] if "name" in idict.keys() else None
        if not name:
            log.error("In-line entry in use_cfgs list does not contain a "
                      "\"name\" key (will be skipped!):\n%s", idict)
            return None

        # Check if temp cfg file already exists
        temp_cfg_file = (self.scratch_root + "/." + self.branch + "__" + name +
                         "_cfg.hjson")

        # Create the file and dump the dict as hjson
        log.log(VERBOSE, "Dumping inline cfg \"%s\" in hjson to:\n%s", name,
                temp_cfg_file)
        try:
            with open(temp_cfg_file, "w") as f:
                f.write(hjson.dumps(idict, for_json=True))
        except Exception as e:
            log.error("Failed to hjson-dump temp cfg file\"%s\" for \"%s\""
                      "(will be skipped!) due to:\n%s", temp_cfg_file, name, e)
            return None

        # Return the temp cfg file created
        return temp_cfg_file

    def _process_overrides(self):
        # Look through the dict and find available overrides.
        # If override is available, check if the type of the value for existing
        # and the overridden keys are the same.
        overrides_dict = {}
        if hasattr(self, "overrides"):
            overrides = getattr(self, "overrides")
            if type(overrides) is not list:
                log.error("The type of key \"overrides\" is %s - it should be "
                          "a list", type(overrides))
                sys.exit(1)

            # Process override one by one
            for item in overrides:
                if type(item) is dict and set(
                        item.keys()) == {"name", "value"}:
                    ov_name = item["name"]
                    ov_value = item["value"]
                    if ov_name not in overrides_dict.keys():
                        overrides_dict[ov_name] = ov_value
                        self._do_override(ov_name, ov_value)
                    else:
                        log.error("Override for key \"%s\" already exists!\n"
                                  "Old: %s\nNew: %s", ov_name,
                                  overrides_dict[ov_name], ov_value)
                        sys.exit(1)
                else:
                    log.error("\"overrides\" is a list of dicts with "
                              "{\"name\": <name>, \"value\": <value>} pairs. "
                              "Found this instead:\n%s", str(item))
                    sys.exit(1)

    def _do_override(self, ov_name: str, ov_value: object) -> None:
        # Go through self attributes and replace with overrides
        if hasattr(self, ov_name):
            orig_value = getattr(self, ov_name)
            if isinstance(ov_value, type(orig_value)):
                log.debug("Overriding \"%s\" value \"%s\" with \"%s\"",
                          ov_name, orig_value, ov_value)
                setattr(self, ov_name, ov_value)
            else:
                log.error("The type of override value \"%s\" for \"%s\" "
                          "doesn't match the type of original value \"%s\"",
                          ov_value, ov_name, orig_value)
                sys.exit(1)
        else:
            log.error("Override key \"%s\" not found in the cfg!", ov_name)
            sys.exit(1)

    def _purge(self):
        '''Purge the existing scratch areas in preparation for the new run.'''
        return

    def purge(self):
        '''Public facing API for _purge().'''
        for item in self.cfgs:
            item._purge()

    def _print_list(self):
        '''Print the list of available items that can be kicked off.'''
        return

    def print_list(self):
        '''Public facing API for _print_list().'''

        for item in self.cfgs:
            item._print_list()

    def prune_selected_cfgs(self):
        '''Prune the list of configs for a primary config file.'''

        # This should run after self.cfgs has been set
        assert self.cfgs

        # If the user didn't pass --select-cfgs, we don't do anything.
        if self.select_cfgs is None:
            return

        # If the user passed --select-cfgs, but this isn't a primary config
        # file, we should probably complain.
        if not self.is_primary_cfg:
            log.error('The configuration file at {!r} is not a primary '
                      'config, but --select-cfgs was passed on the command '
                      'line.'.format(self.flow_cfg_file))
            sys.exit(1)

        # Filter configurations
        self.cfgs = [c for c in self.cfgs if c.name in self.select_cfgs]

    def _create_deploy_objects(self):
        '''Create deploy objects from items that were passed on for being run.
        The deploy objects for build and run are created from the objects that
        were created from the create_objects() method.
        '''
        return

    def create_deploy_objects(self):
        '''Public facing API for _create_deploy_objects().
        '''
        self.prune_selected_cfgs()

        # GUI, GUI debug or Interactive mode is allowed only for one cfg.
        if (self.gui or self.gui_debug or self.interactive) and len(self.cfgs) > 1:
            log.fatal("In GUI mode, only one cfg can be run.")
            sys.exit(1)

        for item in self.cfgs:
            item._create_deploy_objects()

    def deploy_objects(self):
        '''Public facing API for deploying all available objects.

        Runs each job and returns a map from item to status.
        '''
        deploy = []
        for item in self.cfgs:
            deploy.extend(item.deploy)

        if not deploy:
            log.error("Nothing to run!")
            sys.exit(1)

        return Scheduler(deploy, get_launcher_cls(), self.interactive).run()

    def _gen_results(self, results):
        '''
        The function is called after the flow has completed. It collates
        the status of all run targets and generates a dict. It parses the log
        to identify the errors, warnings and failures as applicable. It also
        prints the full list of failures for debug / triage to the final
        report, which is in markdown format.

        results should be a dictionary mapping deployed item to result.
        '''
        return

    def gen_results(self, results):
        '''Public facing API for _gen_results().

        results should be a dictionary mapping deployed item to result.

        '''
        for item in self.cfgs:
            json_str = (item._gen_json_results(results)
                        if hasattr(item, '_gen_json_results')
                        else None)
            result = item._gen_results(results)
            log.info("[results]: [%s]:\n%s\n", item.name, result)
            log.info("[scratch_path]: [%s] [%s]", item.name, item.scratch_path)
            item.write_results(self.results_html_name, item.results_md,
                               json_str, is_primary_cfg=False)
            log.info("[report]: [%s] [%s/report.html]\n\n", item.name, item.results_dir)
            self.errors_seen |= item.errors_seen

        if self.is_primary_cfg:
            self.gen_results_summary(self.batchgroups)
            self.write_results(self.results_html_name,
                               self.results_summary_md, is_primary_cfg=True)
            log.info("[report]: [%s] [%s/report.html]", self.name, self.results_dir)

    def gen_results_summary(self, batchgroups=False):
        '''Public facing API to generate summary results for each IP/cfg file
        '''
        return

    def _add_to_row_dict(self, row_dict, batch_flag, cfg, row):
        '''Checks if the cfgs are divided into batchgroups and adds it to the
        corresponding batchgroup or to the default.
        '''
        if batch_flag:
            if cfg.batchgroup not in row_dict:
                row_dict[cfg.batchgroup] = []
            row_dict[cfg.batchgroup].append(row)
        else:
            row_dict["default"].append(row)

    def write_results(self, html_filename, text_md, json_str=None, is_primary_cfg=False):
        """Write results to files.

        This function converts text_md to HTML and writes the result to a file
        in self.results_dir with the file name given by html_filename.  If
        json_str is not None, this function additionally writes json_str to a
        file with the same path and base name as the HTML file but with '.json'
        as suffix.
        """

        # Prepare reports directory, keeping 90 day history.
        clean_odirs(odir=self.results_dir, max_odirs=89)
        mk_path(self.results_dir)

        # Write results to the report area.
        with open(self.results_dir / html_filename, "w") as f:
            f.write(
                md_results_to_html(self.results_title, self.css_file, text_md, is_primary_cfg))

        if json_str is not None:
            filename = Path(html_filename).with_suffix('.json')
            with open(self.results_dir / filename, "w") as f:
                f.write(json_str)

    def _get_results_page_link(self, relative_to, link_text=''):
        """Create a relative markdown link to the results page."""

        link_text = self.name.upper() if not link_text else link_text
        relative_link = os.path.relpath(self.results_page,
                                        relative_to)
        return "[%s](%s)" % (link_text, relative_link)

    def publish_results(self, repository: str, flow: str):
        """Publish these results to a corresponding repository."""
        log.info("Publishing results to %s", repository)
        repo_dir = os.path.expanduser("./scratch/results_repo")

        env = self._setup_ssh_env()
        self.clone_or_pull(repository, repo_dir, env)

        latest_batch_report = os.path.join(self.scratch_path, 'reports', 'latest', 'report.html')
        # Destination directory should be
        dest_batch_dir = os.path.join(repo_dir, f"{self.name}_{flow}",
                                      f"{self.name}_{flow}_{self.timestamp}",
                                      f"{self.name}", 'reports', 'latest')
        os.makedirs(dest_batch_dir, exist_ok=True)
        shutil.copy2(latest_batch_report, os.path.join(dest_batch_dir, 'report.html'))
        log.info("Copied report for %s", self.name)

        self._write_index_html(os.path.join(repo_dir, f"{self.name}_{flow}"),
                               f"{self.name}_{flow}",
                               f"{self.name}_{flow}_index",
                               f"{self.name}_{flow}_{self.timestamp}",
                               os.path.join(f"{self.name}_{flow}_{self.timestamp}",
                                            self.name,
                                            'reports', 'latest', 'report.html'))

        self._write_index_html(repo_dir,
                               "Reports",
                               "index",
                               f"{self.name}_{flow}",
                               f"{self.name}_{flow}/{self.name}_{flow}_index.html")

        shutil.copy2(os.path.join(self.proj_root, 'util', 'dvsim', 'style.css'), repo_dir)

        for item in self.cfgs:
            latest_report = os.path.join(item.scratch_path, 'reports', 'latest', 'report.html')
            if not os.path.exists(latest_report):
                log.warning("No report found for %s at %s, skipping.", item.name, latest_report)
                continue
            dest_dir = os.path.join(repo_dir,
                                    f"{self.name}_{flow}",
                                    f"{self.name}_{flow}_{self.timestamp}",
                                    os.path.basename(item.scratch_path),
                                    'reports',
                                    'latest')
            os.makedirs(dest_dir, exist_ok=True)
            shutil.copy2(latest_report, os.path.join(dest_dir, 'report.html'))
            log.info("Copied report for %s", item.name)

            if self.args.cov_reports:
                cov_dir = os.path.join(item.scratch_path, 'cov_report')
                if not os.path.exists(cov_dir):
                    log.warning("No coverage reports found for %s at %s, skipping.", item.name, 
                                cov_dir)
                else:
                    cov_dest_dir = os.path.join(repo_dir,
                                                f"{self.name}_{flow}",
                                                f"{self.name}_{flow}_{self.timestamp}",
                                                os.path.basename(item.scratch_path),
                                                'cov_report')
                    os.makedirs(cov_dest_dir, exist_ok=True)
                    shutil.copytree(cov_dir, cov_dest_dir, dirs_exist_ok=True)
                    log.info("Copied coverage reports for %s", item.name)

        subprocess.run(["git", "-C", repo_dir, "add", "-A"], check=True, env=env)
        subprocess.run(["git", "-C", repo_dir, "commit", "-m",
                        f"[dashboard] Update {self.name} {self.flow} {self.timestamp}"],
                       check=True, env=env)
        subprocess.run(["git", "-C", repo_dir, "push"], check=True, env=env)
        log.info("Results published successfully.")

    def _setup_ssh_env(self) -> dict:
        """Return an env dict with SSH configured, using passphrase or deploy key."""
        env = os.environ.copy()
        env["GIT_SSH_COMMAND"] = "ssh -o StrictHostKeyChecking=no"

        passphrase = os.environ.get("SSH_KEY_PASSPHRASE")
        if not passphrase:
            # Rely on deploy key already configured in the environment
            log.info("SSH_KEY_PASSPHRASE not set, assuming deploy key is available.")
            return env

        with tempfile.NamedTemporaryFile(mode='w', suffix='.sh', delete=False) as f:
            f.write(f'#!/bin/sh\necho "{passphrase}"\n')
            askpass_script = f.name
        os.chmod(askpass_script, stat.S_IRWXU)
        env["SSH_ASKPASS"] = askpass_script
        env["SSH_ASKPASS_REQUIRE"] = "force"
        env["DISPLAY"] = ""
        try:
            agent = subprocess.run(["ssh-agent", "-s"], check=True, capture_output=True, text=True)
            for line in agent.stdout.splitlines():
                if "=" in line and ";" in line:
                    key, _, rest = line.partition("=")
                    env[key] = rest.split(";")[0]
            subprocess.run(["ssh-add"], check=True, env=env, stdin=subprocess.DEVNULL)
        finally:
            os.unlink(askpass_script)

        return env

    def clone_or_pull(self, repository: str, local_path: str, env: dict):
        """Clone the repo if it doesn't exist locally, otherwise pull latest."""
        try:
            if os.path.exists(local_path):
                result = subprocess.run(
                    ["git", "-C", local_path, "remote", "get-url", "origin"],
                    check=True, capture_output=True, text=True, env=env
                )
                existing_remote = result.stdout.strip()
                if existing_remote != repository:
                    log.warning("Existing repo at %s points to %s, expected %s. Recloning.",
                                local_path, existing_remote, repository)
                    shutil.rmtree(local_path)
                    subprocess.run(["git", "clone", repository, local_path], check=True, env=env)
                else:
                    subprocess.run(["git", "-C", local_path, "pull"], check=True, env=env)
            else:
                subprocess.run(["git", "clone", repository, local_path], check=True, env=env)
        except FileNotFoundError:
            log.error("git is not installed or not on PATH. Cannot publish results.")
            raise
        except subprocess.TimeoutExpired:
            log.error("Timed out trying to reach repository: %s", repository)
            raise
        except subprocess.CalledProcessError as e:
            log.error("Git operation failed for %s:\n%s",
                      repository, e.stderr.decode().strip() if e.stderr else "")
            raise

    def _write_index_html(self, repo_dir: str, title: str, filename: str, version: str, link: str):
        """Create or update an index html file with a versioned link, kept alphabetically."""
        os.makedirs(repo_dir, exist_ok=True)
        style_src = os.path.join(os.path.dirname(__file__), 'style.css')
        shutil.copy2(style_src, repo_dir)
        filepath = os.path.join(repo_dir, f"{filename}.html")
        if not os.path.exists(filepath):
            html = f"""<!DOCTYPE html>
            <html lang="en">
                <head>
                    <meta charset="utf-8"/>
                    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
                    <title>{title}</title>
                    <link href="style.css" rel="stylesheet"/>
                </head>
            <body style="background-color: #ffffff; margin: 0; padding: 0;">
                <div class="results index-page">
                    <h1>{title}</h1>
                    <table>
                        <thead>
                        <tr><th>Version</th></tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </body>
            </html>"""
            with open(filepath, 'w') as f:
                f.write(html)

        with open(filepath, 'r') as f:
            soup = BeautifulSoup(f.read(), 'html.parser')

        tbody = soup.find('tbody')

        for tr in tbody.find_all('tr'):
            a = tr.find('a')
            if a and a.text == version:
                if a['href'] == link:
                    log.info("Version %s already exists in %s, skipping.", version, filepath)
                    return
                else:
                    a['href'] = link
                    with open(filepath, 'w') as f:
                        f.write(str(soup))
                    return

        new_tr = soup.new_tag('tr')
        new_td = soup.new_tag('td')
        new_a = soup.new_tag('a', href=link)
        new_a.string = version
        new_td.append(new_a)
        new_tr.append(new_td)

        inserted = False
        for tr in tbody.find_all('tr'):
            a = tr.find('a')
            if a and a.text > version:
                tr.insert_before(new_tr)
                inserted = True
                break
        if not inserted:
            tbody.append(new_tr)

        with open(filepath, 'w') as f:
            f.write(str(soup))

    def has_errors(self):
        return self.errors_seen
